// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package info

import (
	"context"
)

const getAllStockInfo = `-- name: GetAllStockInfo :many
SELECT stock_id, name FROM stock_info
`

func (q *Queries) GetAllStockInfo(ctx context.Context) ([]StockInfo, error) {
	rows, err := q.db.QueryContext(ctx, getAllStockInfo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockInfo
	for rows.Next() {
		var i StockInfo
		if err := rows.Scan(&i.StockID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
