// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package postgresql

import (
	"context"
)

const createAccessInfo = `-- name: CreateAccessInfo :exec
INSERT INTO access_log (connected_at) VALUES (NOW())
`

func (q *Queries) CreateAccessInfo(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createAccessInfo)
	return err
}
